[NetLib]
PortExternal=35001
PortInternal=38151
Port=35001

LogLevel=3
SendMaxBufSize=65536
ProcessDataLimit=10000
MaxUserNum=20000
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
UseEncryptPacket=0
DisableReactorPipe=1
ConnectRetryTime=5000
ConnectRetryNum=20
SendMaxBufSizeLinkHandler=52428800
SendMaxBufSizeUserHandler=4194304
UseEncryptPacketIP=127.0.0.1


[AgentShop]
Timer=1:1000,2:10000,5:1800000
ServerNationIdx=1
AgentShopIdx=1
MaxSearchResult=100
CommonIniPath=Common.ini
SearchCacheCount=1023
SearchCacheExpirationMilliSec=60000
PetInfoCacheCount=127
PetInfoCacheExpirationMilliSec=1800000
NoResponseTimeout=1800000
NoActiveLimitTime=120000
CommissionRateBpForSelling=400
CancelSlotCooltimeSec=0
SearchCooltimeSec=1
MyItemCooltimeSec=1
DefaultStackable=100 #36th update
AlertAveragePrice=25
GuildCashbackCheckHour=0

# 42th
#UseCash=0
CommissionRateBpForSellingForcegem=0 # Default(0%)

# 46th
PersonalTradeUsingAlz=0 # Default(0)
PersonalTradeUsingForcegem=1 #지정거래위탁 포스젬 거래 사용 Default(0)
PTAlzCommissionRate=0 # Default(1000/10000=10%)
PTForcegemCommissionRate=500 #Default(500/10000=5%)
UseAgentShopForcegem=0 #Default(0)


[GlobalMgrSvr]
Addr=127.0.0.1
Port=38170


[DBAgent]
Addr=127.0.0.1
Port=38181


[ChatNode]
Addr=127.0.0.1
Port=48111