[NetLib]
PortExternal=35002
PortInternal=48111
Port=35002

SendMaxBufSize=131072
ProcessDataLimit=10000
MaxUserNum=20000
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
DisableReactorPipe=1
LogLevel=5
MemPoolUnitSizeClass=5
ConnectRetryTime=5000
ConnectRetryNum=20
SendMaxBufSizeUserHandler=4194304
SendMaxBufSizeLinkHandler=52428800


[ChatNode]
ServerNationIdx=1
ChatNodeIdx=1
Timer=1:1000,2:10000,4:1000,6:60000,7:10000
ProcessLayerTaskNum=1
NoNotifyTimeLimit=1200000
;NoResponseTimeout=18000000
NoResponseTimeout=180000
NoActiveLimitTime=1200000
BroadCastOverServerNation=0
CharLevelForGuildCreate=40
UseGuildCreateFee=1
AllowGuildBoard=1
LogSay=0

UseRegisterCache=1
CacheUpdateTime=10000
CommonIniPath=Common.ini
UseBuddyBonus=0


[DBAgent]
Addr=127.0.0.1
Port=48211

[GlobalMgrSvr]
Addr=127.0.0.1
Port=38170
