[NetLib]
PortInternal=48211
Port=48211

SendMaxBufSize=131072
ProcessDataLimit=10000
MaxUserNum=100
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
LogLevel=3
MemPoolUnitSizeClass=5
ConnectRetryTime=5000
ConnectRetryNum=20
SendMaxBufSizeLinkHandler=52428800
SendMaxBufSizeUserHandler=4194304

[DBAgent]
ServerIdx=1
DBProcessTNum=10
ProcessLayerThreadsByServerType=233:5
DSN=CabalGame01
Timer=2:60000
UseAchievementRankingSchedule=1
UseMissionFestivalRankingSchedule=1 #Default(0)
UseMailSchedule=1 #Default(0)
UseEventInventorySchedule=1 #Default(0)
UseGuildTreasureRankingSchedule=1 #Default(0)
CommonIniPath=Common.ini

#46th
UseDeletedCharRemoveSchedule=1 #Default(0)

#48th
UseAgentshopSchedule=1 #Default(0)


[DSN]
DBId=sa
DBPwd={{MSSQL_SA_PASSWORD}}
DBAppName=DBAgent_01