[NetLib]
PortInternal=38181
Port=38181

SendMaxBufSize=65536
ProcessDataLimit=10000
MaxUserNum=100
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
LogLevel=4
MemPoolUnitSizeClass=5
ConnectRetryTime=5000
ConnectRetryNum=20
SendMaxBufSizeUserHandler=4194304
SendMaxBufSizeLinkHandler=52428800

[DBAgent]
Timer=1:10000
ServerIdx=1
DBProcessTNum=10
DSN=CabalGame01
UseDungeonRankingSchedule=1
CommonIniPath=Common.ini
UseGuildRankingSchedule=1

# 34th config add
UseBossArena=1

# 42th config add
UseCashServiceSchedule=1
UseLoginEventSchedule=1 # Default(0)

# 46th config add
UseContentsControlSchedule=1 #Default(0)

# 47th config add
UseItemCollectionSchedule=1 #Default(0)

# 48th config add
UseDungeonSpecialObtainList=1 #Default(0)
UseForcecaliburSelectSchedule=1 #Default(0)

# 49th
UseHeilLaboratorySchedule=1 #Default(0)

# 53th
UseEMSSchedule=1 #Default(0)

# 54th
UseFieldBossRaidSchedule=1 #Default(0)

#55th
UseMissionDungeonAddRewardSchedule=1 #Default(0)

#56th
UseChallengeDungeonSchedule=1 #Default(0)
UseBlessingBeadSchedule=1 #Default(0)
IsGameDBAgent=1 #Default(0)

[DSN]
DBId=sa
DBPwd={{MSSQL_SA_PASSWORD}}
DBAppName=DBAgent_01
