[NetLib]
PortInternal=38180
Port=38180

SendMaxBufSize=65536
SendMaxBufSizeUserHandler=4194304
SendMaxBufSizeLinkHandler=52428800
ProcessDataLimit=30000
MaxUserNum=32
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
LogLevel=4
ConnectRetryTime=5000
ConnectRetryNum=20

[DBAgent]
ServerIdx=128
DBProcessTNum=10
DSN=CabalAccount
UseMissinoBattleRankingSchedule=1
Timer=3:60000
CommonIniPath=Common.ini

;(1 : Sun ~ 7 : Sat)
UseMissionBattleRefleshDayoftheWeek=5

# 48th config add
UseRandomWarpDungeonSchedule=1 #Default(0)

[DSN]
DBId=sa
DBPwd={{MSSQL_SA_PASSWORD}}
DBAppName=GlobalDBAgent
