[NetLib]
PortInternal=38170
PortExternal=38170
PortUDP=38170
Port=38170

SendMaxBufSize=65536
ProcessDataLimit=50000
#MaxUserNum=500
WatchsNoPackLimit=100000
SystemLogTTimeOut=100
ReactorTimeOut=-1
LogLevel=3
MemPoolUnitSizeClass=5
ConnectRetryTime=5000
ConnectRetryNum=20
SendMaxBufSizeUserHandler=4194304
SendMaxBufSizeLinkHandler=52428800


[GlobalMgrSvr]
Timer=1:10000,2:300000,3:1000
WorldMaxUserNum=100
NoNotifyTimeLimit=300000
DefaultServerOpen=0
LoadServerAndChannelType=1
SubPasswordCheckIntervalMinute=60
SubPasswordCheckMaxCount=5
UseChangeCCUSystem=1
CommonIniPath=Common.ini
LadderOpen=static;0:17:0:180:100;1:17:0:180:100;2:17:0:180:100;3:17:0:180:100;4:17:0:180:100;5:17:0:180:100;6:17:0:180:100
#LadderOpen=static;0:20:0:180:100;1:20:0:180:100;2:20:0:180:100;3:20:0:180:100;4:20:0:180:100;5:20:0:180:100;6:20:0:180:100
UseSpammerTrap=1
#DailyQDTimeLimitResetTime=0 # (default 0)
#DailyQDTimeLimitDuration=1440 # (default 24*60)
DailyResetTime=0 # Default(0)
DailyResetDuration=1440 # Default(24*60)


[DefaultServerCfg]
Launagues=38653

[Server01]
#ServerType=16

[Server99]

[Server128]

[DBAgent]
Addr=127.0.0.1
Port=38180

[RockAndRoll]
Interval=3600000
RARAddress=127.0.0.1
RARPortNum=32001
Type=0
