[NetLib]
PortExternal=35003
Port=35003


SendMaxBufSize=65536
SendMaxBufSizeLinkHandler=52428800
SendMaxBufSizeUserHandler=4194304
ProcessDataLimit=1024
MaxUserNum=500
WatchsNoPackLimit=10000
SystemLogTTimeOut=100
ReactorTimeOut=-1
LogLevel=4
ConnectRetryTime=5000
ConnectRetryNum=20
UseEncryptPacket=1


[LoginSvr]
GroupIdx=1
Timer=1:30000,2:5000,3:5000
NoActiveLimitTime=40000
TestChannelGroupIdxStartPoint=50
AffiliatedCorpIP=;
client_version={{CLIENT_VERSION}}
NormalClientMagicKey={{NORMAL_CLIENT_MAGIC_KEY}}
UseNotifyServerListUserCount=1

# ImageAuth (OTP)
AuthMaxTryCount=5
AuthWaitTime=120000

# ImageAuth (OLD)
;UseImageAuth=1
#ImageAuthDataPath=./ImageAuth/
;ImageAuthMaxTryCount=5
;ImageAuthWaitTime=120000
;BlockIfImageAuthFail=1
UsePreImageAuth=0
ImageAuthDataPath=/etc/cabal_etc/ImageAuth_Login/
AuthMaxTryCount=5 
AuthWaitTime=120000 

#ServerOder
UseServerListManualOrder=1
ServerListManualOrder=1,2

UseSubPasswordCheckMessage=1

#38th add
ChannelTimeout = 120000 #default:120000ms, 0:NotUsing


#46th add
CommonIniPath=Common.ini

DiGeamAuthWeb=1
DiGeamAuthDB=1
DiGeamOTP=1
DiGeamToken=1
# AuthStep1
#AuthMethodStep1=DiGeamAuthWeb;DiGeamAuthDB

AuthMethodStep1=DiGeamAuthWeb;DiGeamAuthDB

AuthMethodStep2=DiGeamOTP

[DiGeamAuthWeb]
Host={{CABAL_PUBLIC_IP}}:3000
Path=/game-api/game_login
#
[DiGeamOTP]
Host={{CABAL_PUBLIC_IP}}:3000
Path=/game-api/otp_login
#
[DiGeamToken]
Host={{CABAL_PUBLIC_IP}}:3000
Path1=/game-api/get_auth
Path2=/game-api/login_auth
Service=Cabal
ServerID=1100


[HTTPService]
; MOTP, Vasco, PSS, Gash string value


[GlobalMgrSvr]
Addr=127.0.0.1
Port=38170


[GlobalDBAgent]
Addr=127.0.0.1
Port=38180


[SITE_URL]
CASHWEB_URL=https://81.0.219.149:3000/lcAuth/login?v1=
CASHWEB_URL_ODC=https://81.0.219.149:3000/lcAuth/login?prdid=661&v1=
SNS_URL=https://shop.yourdomain.com
GUILDWEB_URL=https://shop.yourdomain.com/CabalGuild/SecureLogin.aspx?Encval=
CASHWEB_URL_CHARGE=https://shop.yourdomain.com/lcAuth/login?v1=
AdditionalURLNum=2
AdditionalURL01=https://81.0.219.149:3000/lcAuth/login?prdid=661&v1=
AdditionalURL02=https://81.0.219.149:3000/lcAuth/login?prdid=661&v1=
