[NetLib]
PortExternal=35021
Port=35021

SendMaxBufSize=131072
SendMaxBufSizeLinkHandler=52428800
SendMaxBufSizeUserHandler=4194304
ProcessDataLimit=10000
MaxUserNum=500
WatchsNoPackLimit=30000
UseEncryptPacket=1
SystemLogTTimeOut=100
ReactorTimeOut=100
DisableReactorPipe=1
ConnectRetryTime=5000
ConnectRetryNum=20
MemPoolUnitSizeClass=5
LogLevel=3

[WorldSvr]
ServerIdx=1
GroupIdx=11
GlobalTimer=4:1000,5:60000,7:3600000,11:1000,17:10,22:60000,24:60000
;GlobalTimer=4:10000,5:60000,7:3600000,11:1000,17:1,22:60000,24:60000
WorldTimer=1:100,2:150,3:3000,6:60000,9:10000,13:150,14:2000,16:200,20:200,21:200,26:1000,28:6000
CommonIniPath=Common.ini
IPAddress={{CABAL_PUBLIC_IP}}
UpdateInterval=300000
UseXignCodeAuth=0
XignCodeModulePath=/home/cabal/XignCode/

DisableSocialSkillSpIncreaseInIWar=1 #Default(1)

ESTPCBangChargeInterval=300000

#NPC distance Check
AutoProcess=;

UseAvoidAgentShopCopy=1
UseRevisionMovingStats=1
UseAllowMoviePosDiff=1
MaxUpperGradeCoreEnchantLv=12

NoIncomingCharDeleteTickCount=60000
OnceIncomingCharacterCount=20

#NonClient Option
UseNonClientCheck=1
NonClientDisAdvantageRate=90

# ALZ_DBHACK_CHECK
#UseAlzDbHackCheck=1
#UseCutIfAlzDbHacked=1

# HackCheckOption
UseCheckSkillCoolTimeHack=1
UseCheckDistanceSkillHack=1
UseBlessingBeadCheck=1
UseHackcheckByTimeScope=1
UseCheckInventoryHack=1

#GameOption
UseMobsChaseModify=1
UseCheckMissionIdx=1
UseHackUserDBSave=0
UseCheckBelongItem=1
ExtraCount=3

#TimeOption
SpeedHackCheckTime=20000
CheckSkillTimeHackScope=60000

#CountOption
UseCheckUserAttack=1
UseDropDiscount=1

# WarNationReward
UseInstantWarNationReward=1

# PShopOpenLimit
PShopOpenLimitCount=300

AllowCashShop=1
UseWorldDrop=1

AllowNetcafePoint=0

LimitLoudCharacterLev=40
LimitLoudMasteryLev=5
UsePvpBetting=0

AllowGuildBoard=0
UseEntryLimitLevel=1
# Channel Attribute Addition: Trade
UseTradeChannelRestriction=0
UseCombatModeRestrictReturnStone=1

# bot check system
UseBotCheckSystem=0
UseImageAuth=0
UseBotCheckInCharacterSelectLogout=0
ImageAuthDataPath=/etc/cabal_etc/ImageAuth/
UseSharedImageAuthData=1
BotAlertInterval=3600000
BotVerifiyTimeout=180
BotMaxVerifyFailCount=3
BeginActStateSleepTime=300
BeginActStatePShopOpenTime=300
BeginActStateSocialActTime=300
ClearActStateAttackingNormalMobTimeout=30
DummyMobList=108;109;110;111;658;704;761;762;763;764;776;777;778;779;780;781;819;820;821;822;876;877;878;915;918;978;979;980;981;982;1079;1093;1094;1095;1096;1097;
 
# invincibility After life during 5 min
UsePreventOttuki=1

# tuning the mission war
#GivePetExpIfMissionWarPvp=1
UseMissAttackInComboMode=0
InstantWarCalledGameType=1
#DisableDancingSpIncreaseIfMissionWar=1

# Load of war
UseLordBroadCastCoolTimeSec=0

# skill balance
AllowAdditionalDmgForMultiHitSkill=1
AllowForceEnchantModeOthersBlessBuff=1
PartyBuffCastableCloseByPartyMemberCount=2

# limit Rank & Entry
UseRankLimitSystem=1
UseEntryLimitLevel=1

#NPC Shop
SoldItemRestoreLimitTime=1440

# warehouse alz limit (0 : unlimit, unit million)
#LimitInventoryAlzSave=600
#LimitWarehouseAlzSave=600
#LimitTradeAlz=400

# 2022-01-21 publisher request 
LimitInventoryAlzSave=10000
LimitWarehouseAlzSave=10000
LimitTradeAlz=9000

# inventory slot hack check
UseCutUserInventoryHack=1

# tune entering mission war

UsePXPenaltyLogicChange=1

#UseSpeedCheck=0


AgentShopRestrictionLv=10
PersonalShopRestrictionLv=10

UseWarExpRewardControl=1

UseOTP=0

# Load (default:0), can't reload
LimitedBroadCastByLord=0

AlzAcquireLimitBlockHours=24

LimitNormalChatLev=0
LimitTradeChatLev=6

UseCheckDistanceSkillHackKickoutCount=20

LimitMegaPhoneCharacterLev=10

UseSkillHackReachToleranceToUser=4
UseSkillHackReachToleranceToMob=4
UseSkillHackRangeToleranceToUser=1
UseSkillHackRangeToleranceToMob=1
UseSkillHackRangeTargetCountTolerance=1


ApexModulePath=/home/cabal/Apex
UseApex=0
UseApexLog=1

AllowDuplicatedPCBangPremium=1

# 29 update chawon port
DimensionPortService=1 

# 33 update config add
ChangeBattleStyle=1

# 34th config add
#AddMeritoriousMedalExchangeTicketCount=3 #180323 0 -> 3
#EventAddHonorMedalScore=30 #180323 add

# 40th add
UseAlwaysSameEntryLimit=1 # default:1(Using)
#battle mission
[Hack]
Enable=1
EnableLog=0
EnableDebugLog=0
SkillMotionEnable=1
SkillMotionTolerance=100
SkillCooltimeEnable=1
SkillCooltimeTolerance=100
SkillReachRangeEnable=1
SkillReachTolerance=4
SkillRangeTolerance=0
SkillReachToleranceMovingMobs=3
SkillReachToleranceMovingUser=10
SkillRangeToleranceMovingMobs=0
SkillRangeToleranceMovingUser=0
SkillCellAttributeEnable=1
SkillSideEffectToleranceTime=200
SkillSideEffectPanaltySynergyEnable=0
LimitMoveHackLogCount=100 # Default(100)


[TPoint]
Use=FALSE
UseTPointOnlyBeadPlusUser=1
MaxPoint=20000
BasisPoint=1
UpdateSpan=600

[DBAgent]
Addr=127.0.0.1
Port=38181

[DBAgentAll]
List=43:127.0.0.1:38180,44:127.0.0.1:38180,45:127.0.0.1:38180


[CashDBAgent]
Addr=127.0.0.1
Port=38190

[ChatDBAgent]
Addr=127.0.0.1
Port=48211


[PCBangDBAgent]
Addr=127.0.0.1
Port=38140


[EventMgrSvr]
Addr=127.0.0.1
Port=38200


[PartySvr]
Addr=127.0.0.1
Port=48171


[GlobalMgrSvr]
Addr=127.0.0.1
Port=38170


[ChatNode]
AddrForServer=127.0.0.1
PortForServer=48111
AddrForClient={{CABAL_PUBLIC_IP}}
PortForClient=35002
Port=35002


[AgentShop]
AddrForServer=127.0.0.1
PortForServer=38151
AddrForClient={{CABAL_PUBLIC_IP}}
PortForClient=35001
UseGuildExpansion=1
UseAgentShop=1

[StunSvr]
AddrForClient={{CABAL_PUBLIC_IP}}
PortForClient=38110
UdpPortForClient=48110
