[program:GlobalDBAgent]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/GlobalDBAgent -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:RockAndRoll]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/RockAndRoll -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:GlobalMgrSvr]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/GlobalMgrSvr -c'
user=root
autostart=false
autorestart=unexpected
startsecs=12

[program:EventDBAgent]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/EventDBAgent -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:PCBangDBAgent]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/PCBangDBAgent -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:EventMgrSvr]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/EventMgrSvr -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:LoginSvr_01]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/LoginSvr_01 -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3

[program:StunSvr]
directory=/etc/cabal_etc/core/
command=/bin/bash -c 'exec /usr/bin/StunSvr -c'
user=root
autostart=false
autorestart=unexpected
startsecs=3
